### ISSUE TITLE
Create the Vue frontend

### ISSUE THREAD

**Issue by PumpkinSeed** [nyrbrg/flowfluence#2]
Create a new app based on Vue, it will be served by static pages from the Go webserver on the /public route. 

Look around is it possible, and if yes, how?

**Comment by borosr** [comment]
Yes, it's possible, there is a dummy project for that: https://github.com/borosr/go_vue
I also created a static endpoint for file serve, maybe this will help us for the resource download

**Comment by borosr** [comment]
I'll start to implement a basic vue SPA based on this tutorial: https://developer.okta.com/blog/2018/10/23/build-a-single-page-app-with-go-and-vue
Are you agree to that?

**Comment by PumpkinSeed** [comment]
While the logic is Vue static pages served by a Go webserver, that's all fine for me.

**Comment by PumpkinSeed** [comment]
While the logic is Vue static pages served by a Go webserver, that's all fine for me. 

Close this issue, because that means the end of this issue and the start of the #3

**Comment by PumpkinSeed** [comment]
While the logic is Vue static pages served by a Go webserver, that's all fine for me.

Close this issue, because that means the end of this issue and the start of the #3
